### PR TITLE
Fixes circular component sizing functionality for all devices. Fix #9

### LINKED ISSUE #9: circular graphic component
Since for all the pages we are using the circular graphic, it would be great to have one single component that can be reused on all the pages. We can pass on the styles as props to that component. I have added [Rebass](https://rebassjs.org/) and [styled-components](https://www.styled-components.com/) which might help to build this.
Another option, an easy way out is to make graphics and use it as background image.

### PR DESCRIPTION
**Pull request by Amorpheuz**
Fixes sizing issues of #9 

The circular component should scale properly on all devices now, Set it's width to be 40% of the screen.

In order to modify how the circle looks and it's positioning, modify `SemiCircleContainer`, while color of the semicircle can be modified via `SemiCircle` Component.

**Preview:**
- Right Side
image

- Left Side
image

### CODE REVIEW

**Comment by harshil1712** [comment]
This still doesn't fix the issue. I was setting the height more than 100% so that we could set its position (top) such that the we get the expected result. We don't want the whole semi circle. Compare your result with the design, focus more on the top and bottom, you will understand what I mean to say.

**Comment by Amorpheuz** [comment]
Yup, I noticed it later in the night, I have got another idea which I will hopefully get done with today... That one should work flawlessly

**Comment by harshil1712** [comment]
Did you solve the issue for left side?

**Comment by Amorpheuz** [comment]
Done with full circular component setup for desktop that is. Setup 3 different variations of the component, a left, right and one specific to home with more negative space.

Is this the confirmed mobile design?
image

If so, I can setup another top variation for the same. Do you recommend having media queries as outlined [here](https://material-ui.com/components/use-media-query/#ThemeHelper.js) for switching between top and desktop?

**Comment by harshil1712** [comment]
Since you have created the component using styled-compnents I prefer not to
include material design here

**Pull request closed without merging**
