### PR TITLE
Added team page, just copy the css into css file

### PR DESCRIPTION
**Pull request by meetsavani**
Added team page code.
If someone finds effective bootstrap classes for my CSS then please do tell.

### CODE REVIEW

**Comment by arps18** [comment]
Few Changes Required:

- Use Font Zilla Slab

- Avoid Horizontal Scrolling so work on that

- 3 Cards in a column would be more effective

- After 3 Cards in a Column, Increase the width of the card a bit. You are free to use your own dimensions but in the end it should cover the screen effectively.

- Add LinkedIn As well in social Media

That's It. Keep Going @meetsavani

**Comment by meetsavani** [comment]
Font added, Horizontal scrolling removed
Also, check out https://meetsavani.github.io/frontend1.github.io/ for 3 cards in a row,
if you want, I can add that changes here
But I think 4 cards in a row are better than 3.
share thoughts

**Comment by arps18** [comment]
- The 3 Cards looks more appealing acc. to me!

- Kindly use font Zilla Slab everywhere, right from Heading to details!

Rest appears fine to me! Good job!

**Review by arps18 — CHANGES_REQUESTED** [review]
-  The 3 Cards looks more appealing acc. to me!

 -  Kindly use font Zilla Slab everywhere, right from Heading to details!

Rest appears fine to me! Good job!

**Comment by meetsavani** [comment]
Done

**Review by arps18 — APPROVED** [review]

**Comment by arps18** [comment]
Great Work @meetsavani🎉Now we will wait for the other components to be completed, after that you are requested to do the following changes:

- When you merge the page with the current one, Make sure the Header size matches with the Event Page

- Add the images,description and links which will be provided to you!

**Pull request closed without merging**
